exports.alreadyLoginTxt = 'Already Have an account ?'
exports.newUserRegisterTxt = 'Do you have account?'
exports.loginTxt ='Login'
exports.registerTxt = 'Register'
exports.registerwelcomeTxt = 'Welcome to'
exports.rdStoreTxt ='RD STORE'
exports.userNameTxt = 'Username'
exports.emailTxt = 'Email'
exports.passwordTxt = 'Password'
exports.orTxt='or';
exports.signupWithGoogleTxt ='Sign up with google'
exports.loginWithGoogleTxt ='Google'

exports.userEndPoint = 'api/user/'
exports.addUserEndPoint = 'register'
exports.loginUserEndPoint = 'login'